### ISSUE TITLE
purge empty fields from the output

### ISSUE THREAD

**Issue by errordeveloper** [errordeveloper/kubegen#11]
Right now we get things like this:
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /prometheus
    creationTimestamp: null
    labels:
      name: cart
    name: cart
  spec:
    ports:
    - name: http
      port: 80
      targetPort: http
    selector:
      name: cart
  status:
    loadBalancer: {}
```
and we should really see this instead:
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /prometheus
    labels:
      name: cart
    name: cart
  spec:
    ports:
    - name: http
      port: 80
      targetPort: http
    selector:
      name: cart
```
