### ISSUE TITLE
short-hand macro syntax

### ISSUE THREAD

**Issue by errordeveloper** [errordeveloper/kubegen#40]
Consider the following snippet:
```YAML
kubegen.String.Join:
        - kubegen.String.Lookup: images/ide-basename
        - '@sha256:'
        - kubegen.String.Lookup: images/ide-digest
```

This could be much shorter and still readable, e.g.:

```YAML
kubegen.String.Join: [{.Lookup: images/ide-basename}, '@sha256:' {.Lookup: images/ide-digest}]
```

This will become more important when branching (#39) gets implemented.
