### ISSUE TITLE
use of object in internal attributes becomes more like functions

### ISSUE THREAD

**Issue by errordeveloper** [errordeveloper/kubegen#41]
Right now we have something like:

```YAML
Kind: kubegen.k8s.io/Module.v1alpha2

Parameters:

  - Name: images/ide-basename
    Type: String
    Default: errordeveloper/k9c
  - Name: images/ide-digest
    Type: String
    Default: ad69086ac28b91c745ecd8be2d21e1f1630d81c9eeb6967338c9f73794780475

  - Name: namespaces/ide
    Type: String
    Default: ide


Deployments:

  - name: ide
    namespace: {kubegen.String.Lookup: namespaces/ide}
    replicas: 1
    sericeAccount: ide
    initContainers:
      - name: git-clone
        image: {kubegen.Object.Lookup: internals/images/ide-name}

Internals:

  - Name: internals/images/ide-name
    Type: Object
    Value:
      kubegen.String.Join:
        - kubegen.String.Lookup: images/ide-basename
        - '@sha256:'
        - kubegen.String.Lookup: images/ide-digest
```

It works, however, it's unclear how come `internals/images/ide-name` is an object, while the last thing it calls is supposed to return a string, and even less clear why we look it up as an object.

We probably need to re-think the type system a little bit and consider renaming internal object attributes to some kind of functions.
